name: project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.4
  sign_in_with_apple: ^7.0.1
  google_fonts: ^6.1.0
  table_calendar: ^3.0.8
  syncfusion_flutter_calendar: ^29.1.39
  file_picker: ^10.1.2
  http: ^1.2.0
  installed_apps: ^1.6.0
  syncfusion_flutter_pdf: ^29.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/hidden.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/visible.png